### ISSUE TITLE
Why not use plain "mega" wheels?

### ISSUE THREAD

**Issue by pombredanne** [cloudify-cosmo/wagon#101]
I wonder why you did not elect to create aggregated wheels instead which is a scenario that has been always support by wheel? (eg rewheeling several wheels in one single wheel?)

**Comment by nir0s** [comment]
Hmm, can you please provide reference for that? Thanks

**Comment by pombredanne** [comment]
Well, my bad, this is supported to be supported by the wheel format though there is nothing available to actually do this. And there have been little or few discussions except... from you!

So please ignore this.

And I see you actually researched this quite a bit:
- https://groups.google.com/forum/#!topic/distutils-sig/Qm_1MrJrJnk
- https://github.com/pypa/pip/issues/3848

And you are not the only here: http://stackoverflow.com/questions/35637768/how-to-package-multiple-python-wheels-into-one-wheel-on-windows

There are also some talks in there: http://stackoverflow.com/questions/35637768/how-to-package-multiple-python-wheels-into-one-wheel-on-windows

That said, I am doing something not exactly the same but to answer a similar concern: e.g. package and distribute a complete application with its wheels.. I use a pip wrapper https://github.com/nexB/scancode-toolkit/blob/develop/etc/configure.py with some minimal requirements files: https://github.com/nexB/scancode-toolkit/tree/develop/etc/conf and vendor the built wheels: https://github.com/nexB/scancode-toolkit/tree/develop/thirdparty/prod

**Comment by pombredanne** [comment]
And while the pants  pex format might quite close this is not wheels: https://pex.readthedocs.io/

**Comment by nir0s** [comment]
yeah, pex is not quite what I was looking for. I looked into pex as well when I started looking at this problem.

**Comment by nir0s** [comment]
_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
