### ISSUE TITLE
Change subcommand names to be consistent with `wheel`

### ISSUE THREAD

**Issue by nir0s** [cloudify-cosmo/wagon#103]
Wheel's API provides the following:

* wheel.archive
* wheel.install
* wheel.pkginfo
* wheel.util

Maybe we should change the names of the subcommands to:

* wagon archive (instead of create)
* wagon pkginfo (instead of show)

WDYT?

**Comment by geokala** [comment]
From discussion with @tehasdf, this probably isn't worth doing- it'd require an API change and make the command names less obvious for those who aren't familiar with wheel. Closed.
