### ISSUE TITLE
Won't create wagon without virtualenv... while in a virtualenv

### ISSUE THREAD

**Issue by 01000101** [cloudify-cosmo/wagon#107]
I have a virtualenv that's activated but that virtualenv does not have virtualenv installed (nor is it installed globally). Wagon fails due to a validation error that virtualenv is not available. I really can't imagine that this has an actual requirement (unless Wagon is creating its own virtualenv?!?) so I'm wondering why this is a fatal-error-level issue. 

```
(venv) [gibson ~]$ wagon create -o ./wbuild --validate -v airflow
virtualenv is not installed and is required for the validation process. Please make sure virtualenv is installed and is in the path. (You can run 'pip install wagon[venv]')

(venv) [gibson ~]$ env | grep VIRTUAL_ENV
VIRTUAL_ENV=/home/ec2-user/venv
```

**Comment by nir0s** [comment]
RTFD :)

When you use the `--validate` flag, wagon uses virtualenv directly to validate the generated wagon archive. If you install wagon inside the virtualenv but don't have virtualenv available within the path, simply run `pip install wagon[venv]` and it will install the relevant virtualenv version for you.
