### ISSUE TITLE
`wagon install` leaves a temporary directory behind

### ISSUE THREAD

**Issue by OddBloke** [cloudify-cosmo/wagon#108]
When performing an install with wagon 0.6.0, I see the following lines in the console output (with the app name replaced):

```
Extracting zip .../foo.wgn to /tmp/tmpWN6MLw...
Source is: /tmp/tmpWN6MLw/foo
```
Once installation is complete, `/tmp/tmpWN6MLw` still exists. This has caused a disk space issue for us in a Jenkins environment where we are installing wagons a lot.

**Comment by OddBloke** [comment]
Actually, digging in to this further, the temporary directory is left in place but the _contents_ are now deleted. So we won't see the disk space issue, but I'm leaving this open because the temporary directory is still left behind.

(This is a change from the version we're using in production ATM, and I just checked for the existence of the temporary directory after a run with 0.6.0.)

**Comment by nir0s** [comment]
@OddBloke, might I ask for your use case? Trying to learn how people are using wagon.

**Comment by OddBloke** [comment]
On Thu, Jul 06, 2017 at 08:31:58AM +0000, Nir Cohen wrote:
> @OddBloke, might I ask for your use case? Trying to learn how people are using wagon.

We have a tool which registers the Ubuntu cloud images in to each cloud.
The tool gets updated often enough that having a single shared
installation on our workers wouldn't be practical, so we install it
afresh per-run.  The runs can be highly parallel, and we depend
(transitively) on a number of packages which require compilation at
install-time, so installation is very IO and CPU heavy.  Creating binary
wheels once is obvious solution to this, and wagon makes that very easy.

(It also allows us to have a single artifact that we can move through a
CI pipeline, though our CI is still fairly nascent.)

**Comment by OddBloke** [comment]
Thanks @nir0s!
