### ISSUE TITLE
pip 10.0.0 breaks wagon

### ISSUE THREAD

**Issue by nir0s** [cloudify-cosmo/wagon#120]
pip 10 was released yesterday and is currently breaking Wagon. The `--use-wheel` flag was removed from pip and replaced by `--only-binary`.

**Comment by djay87** [comment]
When will this be fixed ?

**Comment by nir0s** [comment]
We'll release a version with a fix in the next few days.

**Comment by richardwhiuk** [comment]
Any chance of a release of wagon with this in it?
