### ISSUE TITLE
Wagon release 0.8.0 with pip >= 10 compatibility?

### ISSUE THREAD

**Issue by bjgill** [cloudify-cosmo/wagon#125]
From the README:

> If you're using pip>=10.x, please make sure you use wagon>=0.8.0

As far as I can tell, wagon 0.8.0 hasn't yet been published. Would it be possible to get a release so we can take the fix for https://github.com/cloudify-cosmo/wagon/issues/120 and start using wagon with pip >= 10.x?

**Comment by cswindle** [comment]
I believe that there were changes in the wagon format, if that is the case would 0.8.0 support producing wagons that are compatible with Cloudify manager 4.3?

**Comment by geokala** [comment]
0.9.1 has now been released which should support pip >= 10
Please reopen this if you run into problems with it, and sorry for the massive delay on this response.
