### ISSUE TITLE
Wagons install in cloudify management 3.2

### ISSUE THREAD

**Issue by tommyjcarpenter** [cloudify-cosmo/wagon#25]
I went through the process of building "waggoned" plugins. 

We are still using the 3.2 version of the Cloudify management server. It tries to pip install our Wagonned plugins, which fails, because there is no longer a setup.py file. 

Is there any way to use wagons with cloudify 3.2?

**Comment by nir0s** [comment]
Unfortunately no. Wagon based plugin installation is only supported from
3.3 onwards.
