### ISSUE TITLE
Wagon ignores output directory

### ISSUE THREAD

**Issue by idanmo** [cloudify-cosmo/wagon#35]
When running wagon against a file system source project, it keeps trying to create the package in the current directory. For example, if the source project is in the current directory, it complains that the directory already exists. If I move to another directory (like /tmp, which is set as the output directory anyway) it works fine.

**Comment by nir0s** [comment]
That is caused due to wagon creating a subdirectory for all of its resources which is under the name of the package itself.. so if you're creating a wagon right within that same package's dir, this will happen. I guess the solution would be to generate everything in /tmp
