### ISSUE TITLE
Wagon 0.3.1 breaks creation and installation on Windows

### ISSUE THREAD

**Issue by nir0s** [cloudify-cosmo/wagon#41]
Wagon 0.3.1 uses `sys.executable` as a reference to where `pip` is found. In Windows, that might not be in the `sys.executable`'s path but rather under `scripts`. The tests are not broken since both Travis and Circle provide a build in version of Python where pip is available in the correct path.

We should provide special treatment for Windows.

**Comment by nirfuchs** [comment]
Sent a PR for this issue, see https://github.com/cloudify-cosmo/wagon/commit/703bb8f28aafa3b50662a9c6dca5322c550b0416

**Comment by nir0s** [comment]
Um.. tests aren't passing :)

**Comment by nirfuchs** [comment]
Turns out that tests on master were broken due to cloudify-script-plugin dependencies.
I've submitted a separate PR #43 to fix this so once #43 is pushed I'll rebase this one and replay the tests once again to make sure I did not introduce any other failures.
