### ISSUE TITLE
Support `manylinux1` tag via auditwheel

### ISSUE THREAD

**Issue by nir0s** [cloudify-cosmo/wagon#52]
While we can declare that wagon only supports `manylinux1` if the wheels in it are `manylinux1`, I think we should add the ability to convert `linux_x64_86` to `manylinux1` to make the job a bit more comfortable for the user.

Relevant links:
- [This PEP](https://www.python.org/dev/peps/pep-0513/) describes the tag.
- [Auditwheel](http://github.com/pypa/auditwheel)

Since auditwheel requires Centos 5 (not older) to work (due to forward backward compat of glibc), we can verify that version of the distribution and only if it's Centos 5-, allow to run `wagon repair` which will recursively repair all wheels in the wagon and recreate the wagon.

To test creating a `manylinux1` compat wheel, try

``` bash
$ docker run -i -t -v `pwd`:/io quay.io/pypa/manylinux1_x86_64 /bin/bash
$ /opt/python/cp35-cp35m/bin/pip wheel flask
$ auditwheel repair MarkupSafe-0.23-cp35-cp35m-linux_x86_64.whl
...

Repairing MarkupSafe-0.23-cp35-cp35m-linux_x86_64.whl
Previous filename tags: linux_x86_64
New filename tags: manylinux1_x86_64
Previous WHEEL info tags: cp35-cp35m-linux_x86_64
New WHEEL info tags: cp35-cp35m-manylinux1_x86_64

Fixed-up wheel written to /wheelhouse/MarkupSafe-0.23-cp35-cp35m-manylinux1_x86_64.whl
...
```

WDYT?

**Comment by nir0s** [comment]
Btw, this also renders appending the distribution and release to the wagon file name redundant.

**Comment by nirfuchs** [comment]
@nir0s what if we don't convert linux_x86_64 to manylinux1 in this case. would it even work as expected?

**Comment by nir0s** [comment]
@nirfuchs it will probably not work due to cross-distro glibc compat issues.

**Comment by nir0s** [comment]
I supplied a `repair` command (corresponding with auditwheel's repair command) which will repair all linux wheels to manylinux1, repack it, and update the metadata. This obviously requires the same environment required by auditwheel so it can't just be run anywhere.

**Comment by makslevental** [comment]
@nir0s can you support passing args to auditwheel just as you do for pip? at minimum `--plat`?
