### ISSUE TITLE
Logging by wagon should be more explicitly configurable

### ISSUE THREAD

**Issue by dankilman** [cloudify-cosmo/wagon#72]
1) The wagon logger logs is set to INFO level by default, perhaps this should be changed to DEBUG
2) The functions exposed by the module have a `verbose` flag (which is just fine). Only problem is that this flag sets the logger logging level on each invocation. This may lead to unexpected behavior by users that may configure loggers in their app, etc...

**Comment by nir0s** [comment]
Wagon should probably be rather verbose by default. I agree we should make it DEBUG by default and add some additional information which is beyond debug when providing the verbose flag.
